app:
    service_name: "alarm"
    log_file: "logs/app"
    log_level: "INFO"
    interval: 30
    channel_size: 100

database:
    db_type: mysql
    db_host: 127.0.0.1
    db_port: 3306
    db_name: dbname
    username: "user"
    password: "password"
    charset: utf8mb4

redis:
    network: tcp
    address: "127.0.0.1:6379"
    auth:
    max_idle: 5
    idle_timeout: 240
    db_select: 0
    queue_name: "ywb.alarm.queue"
    touch_name: "ywb.alarm.touch"
    stats_name: "ywb.alarm.stats.hash"
