app:
    servicename: "alarm"
    logfile: "logs/app"
    loglevel: "INFO"
    interval: 30
    channelsize: 100

db_config:
    db_type: mysql
    db_host: 127.0.0.1
    db_port: 3306
    db_name: dbname
    username: "user"
    password: "password"
    charset: utf8mb4

redis:
    network: tcp
    address: "127.0.0.1:6379"
    password: 
    maxidle: 5 
    idletimeout: 240
    db: 0
    queuename: "ywb.alarm.queue"
    touchname: "ywb.alarm.touch"
    statsname: "ywb.alarm.stats.hash"